### ISSUE TITLE
Initial data model

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/data#1]
# Data Model
## Event
- Start date can have several resolutions (year, year+month, year+month+day)
- End date is optional and signifies an interval if existant
- Time is optional on an event
- place foreign key
- map-context choice for "zoom level"
- map-position custom JSON field uneditable
- people M2M
- annotation M2M (through Annotation)
## Annotation

A M2M object that groups together many events
- events M2M, main 
- places M2M, an additional connection to places, besides event-place (e.g. for paths)
- need way to specify some hierarchy, such as parent-children
## Places
- a geocoding mechanism for mapping place-coordinate
- need ability to add metadata (alternative naming, political entities)
## Person
- date of birth death, need flexible resolutions
- places M2M for lived/worked
- single media avatar
- needs O2M alternative names
## Organizations
- Same as Person (including related places)
## Media
- File with lots of metadata
- Fixed category types
## Projects
- Project metadata
## Researchers
- Extends base user object
- Some additional fields

**Comment by yuvadm** [comment]
Initial admin is up and running, credentials sent out privately @mushon @josefspr

**Comment by josefspr** [comment]
Hi Yuval, looks quite elegant, thanks. Initial remarks: 
Save researcher causes error
Dates - better date selector interface, 2 resolutions: dd-mm-yyyy and yyyy
Titles in general too short, maybe drag enlarge
Media upload very slow, 2.5M takes forever. Are there limitations here ?
People - field for Hebrew name
Organization - place is not mandatory.
Event - people, organization not mandatory
Combo lists - deselect doesn't work
Add media to event - I think that combo list is not so good, I like 
the wordpress style of media browser.
Not consistent when does popup window opens and when a new tab.
Assigning places to events- in our meeting we talked that there is a field for alt place name
that will display the list of alt names of selected place (there can be a number of alt names for
each place in a couple of languages). right Mushon ?
Event - field for political entity of place (country, empire, province). There should be a meta data for
these entities. right Mushon ?
Research field in event missing.
Filters on lists of data records ( owner, research - for events etc)
Annotations - annotations are between events AND event -> place, right ?
missing directionality, add type: reference
what about source/parenthood ? a recording in Jerusalem 2015 of a song in Belarus 1914
Is this case a parent/child relationship (parent Belarus, child Jerusalem) ? Mushon ?
Annotation in list should be indentifiable by their event names, places etc

**Comment by yuvadm** [comment]
> Save researcher causes error

Fixed

> Dates - better date selector interface, 2 resolutions: dd-mm-yyyy and yyyy

There's no nice way to do this. If I put a proper date selection widget there's no way to specify just a year or a month. Also those widges break for old dates, how do you scroll back to the year 1400? I'm open to other suggestions.

> Titles in general too short, maybe drag enlarge

Which titles?

> Media upload very slow, 2.5M takes forever. Are there limitations here ?

The bottleneck will always be your internet connection. How long did it take? 2.5M should take no more than 30 seconds.

> People - field for Hebrew name
> Organization - place is not mandatory.
> Event - people, organization not mandatory

Will handle.

> Combo lists - deselect doesn't work

Deselect works for me. If you see a field that is required (i.e. forces at least one selection) but shouldn't be, let me know which one it is.

> Add media to event - I think that combo list is not so good, I like the wordpress style of media browser.

I'll see if we can implement something similar.

> Not consistent when does popup window opens and when a new tab.

In which case?

> Assigning places to events- in our meeting we talked that there is a field for alt place name
> that will display the list of alt names of selected place (there can be a number of alt names for
> each place in a couple of languages). right Mushon ?

Yes, need to find a smart way to add this.

> Event - field for political entity of place (country, empire, province). There should be a meta data for
> these entities. right Mushon ?

I don't recall this but I can add if neccesary.

> Research field in event missing.

OK

> Filters on lists of data records ( owner, research - for events etc)

Please explain

> Annotations - annotations are between events AND event -> place, right ?

we have both, yes

> missing directionality, add type: reference

OK

> what about source/parenthood ? a recording in Jerusalem 2015 of a song in Belarus 1914
> Is this case a parent/child relationship (parent Belarus, child Jerusalem) ? Mushon ?

Can add if we want it.

> Annotation in list should be indentifiable by their event names, places etc

OK

**Comment by josefspr** [comment]
Research - missing field for researcher
Date -  Resolution: 1939-00-00 = year, 1939-05-00 =month, 1939-05-12 =day  ?
Length of title field: E.g. - in research form - I cannot see all the line of Kol Mekadesh
Upload - I have 12M and gets stuck, can you add upload progress bar ?
Deselect combo box - works (with mac need command key....)
Annotation - place is not mandatory (between 2 events)
Filter on lists - E.g: In list of events I want to see only the events I uploaded or only the events related to the research I am working on.

**Comment by mushon** [comment]
Hey guys,
fust a quick process recommendation to do this bug reports as individual Github issues to be tracked and addressed separately.
Cheers,
-- 
Mushon Zer-Aviv
Mushon.com | Shual.com | @mushon

On November 13, 2015 at 7:13:42 AM, josefspr (notifications@github.com) wrote:

Research - missing field for researcher
Date - Resolution: 1939-00-00 = year, 1939-05-00 =month, 1939-05-12 =day ?
Length of title field: E.g. - in research form - I cannot see all the line of Kol Mekadesh
Upload - I have 12M and gets stuck, can you add upload progress bar ?
Deselect combo box - works (with mac need command key....)
Annotation - place is not mandatory (between 2 events)
Filter on lists - E.g: In list of events I want to see only the events I uploaded or only the events related to the research I am working on.

**Comment by josefspr** [comment]
yes. you're right...

Date: Fri, 13 Nov 2015 01:29:10 -0800

**Comment by yuvadm** [comment]
Most of these items have been fixed in commits today. Closing this issue, please open new issues for anything else.
