### ISSUE TITLE
title field too short

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#13]
this is what I meant:
<img width="521" alt="screen shot 2015-11-15 at 7 26 03 pm" src="https://cloud.githubusercontent.com/assets/15631729/11169967/34336032-8bcf-11e5-949a-9159354d440d.png">

**Comment by yuvadm** [comment]
@josefspr Is it just this field that's too short? I can make it bigger, but need to think about the context of how it might show up on the map.

**Comment by josefspr** [comment]
I think the researches can be quite long, but Mushon should give the limit.
Maybe there should be title and short title.

**Comment by yuvadm** [comment]
+1 for title and subtitle.

**Comment by mushon** [comment]
:+1:
Let's have a mandatory title field and an optional subtitle.

**Comment by yuvadm** [comment]
We now have subtitles, so this ticket is invalid
