### ISSUE TITLE
filter by owner

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#14]
I think there should also be filter by creator of event, should appear in event list info

**Comment by yuvadm** [comment]
we don't currently have a notion of a "creator" on the database objects. do you think this will be a useful addition? no complexity on my side to do this.

**Comment by josefspr** [comment]
I think so, because of the delete issue and also a couple of researchers may be working on the same research, so each one should know his events

Date: Sun, 15 Nov 2015 10:45:46 -0800

**Comment by yuvadm** [comment]
Track on #15
