### ISSUE TITLE
Alternative place names

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#17]
and a place can have more than 1 alt names

**Comment by yuvadm** [comment]
this is a M2M field on Place, and should also be choosable from the event itself.

**Comment by yuvadm** [comment]
Gonna try and implement this as an ArrayField.

**Comment by yuvadm** [comment]
https://bradmontgomery.net/blog/nice-arrayfield-widgets-choices-and-chosenjs/

https://bradmontgomery.net/blog/django-admin-filters-arrayfields/

This looks good for tagging https://harvesthq.github.io/chosen/

**Comment by yuvadm** [comment]
Later on we can look into widegtizing this field in the admin if it becomes a popular flow, but for now it's not worth the effort.

**Comment by mushon** [comment]
Yeap, Chosen looks great. Something along these lines could possibly be useful for the front-end filtering too

**Comment by yuvadm** [comment]
Agree, we might need this anyway, but the Django admin integration is a bit overkill at this point.

**Comment by mushon** [comment]
https://github.com/theatlantic/django-chosen ?

**Comment by mushon** [comment]
I remembered [Select2](https://select2.github.io/) indeed was a cool option.
And it looks like it has even more [features we can use](https://select2.github.io/examples.html#data-ajax) and it was also [implemented in Django](https://github.com/theatlantic/django-select2-forms).

**Comment by yuvadm** [comment]
Two important points here:
1. For the admin I need something that works with [`ArrayField`](https://docs.djangoproject.com/en/1.8/ref/contrib/postgres/fields/#arrayfield), which none of the existing projects do.
2. For the front-end, start aiming for react components - we're no longer in jQuery land :wink:

**Comment by mushon** [comment]
Like this?
http://jedwatson.github.io/react-select/

**Comment by yuvadm** [comment]
:heart_eyes_cat:

**Comment by yuvadm** [comment]
For the admin https://github.com/applegrew/django-select2/issues/226 seems like the best bet.

**Comment by josefspr** [comment]
we did not finish yet with this one, right ?

**Comment by yuvadm** [comment]
We are finished with this ticket. Now tracking on #47

**Comment by yuvadm** [comment]
Solved as in #47

**Comment by josefspr** [comment]
I would like to see the alternative names of a place as a drop down in the event.

**Comment by yuvadm** [comment]
Sure, but let's track this separately.
