### ISSUE TITLE
field for name of political entity

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#18]
still not implemented

**Comment by yuvadm** [comment]
We agreed to resolve this using the alt names field #17

**Comment by josefspr** [comment]
sorry to nag about this one, I think alt names does not resolve this.
I don't want to attach entity to alt names like "St. petersburg, Russian Empire", "St. Petersburg, Russia"

**Comment by yuvadm** [comment]
so what's the suggested alternative in this case?

**Comment by yuvadm** [comment]
#47 is tracking the upstream bug that's keeping from implementing this.
