### ISSUE TITLE
Launch deployment environment

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/data#2]
Initial deployment environment is required for content upload to take place
- [x] Heroku setup
- [x] Basic dev plan postgres
- [x] S3 media integration

**Comment by yuvadm** [comment]
We're up on https://daat-hamakom.herokuapp.com

**Comment by mushon** [comment]
Beautiful ;)

**Comment by yuvadm** [comment]
You need to be able to find your way to where all the cool kids are hanging out :laughing:
