### ISSUE TITLE
question: what is the difference between annotation type and link style ?

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#20]

**Comment by yuvadm** [comment]
this is as specified in the google doc. @mushon any idea here? might be a mistake and if so i'll remove it.

**Comment by mushon** [comment]
It's not a mistake, but we might give it up. The idea was that we might have more than one style for arrows for example. Either way, we can account for it in the annotation type (arrow, big arrow… etc)

**Comment by yuvadm** [comment]
If we ever implement arrow styles we'll add this field. Closing for now.

**Comment by josefspr** [comment]
reminding to remove the link type field
