### ISSUE TITLE
publish toggle should be on top

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#23]
Else people will miss it. maybe better to even make a publish/unpublish button ?

**Comment by yuvadm** [comment]
if this is just a field that content editors will just mark and carry on, then we just added overhead for no good purpose. let's try to think of how this will be used in real life, and if there's any one gatekeeper that will be going over the new content and approving, or something similar.

**Comment by josefspr** [comment]
I was not thinking of a gatekeeper, just that the content editor can view the map in preview mode
and then publish the contents.
