### ISSUE TITLE
so how do we deal child/parent relationship ?

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#26]
They both share a lot of the same data, except place/time, so I do not want 
to fill up the child data again.
perhaps there is a parent event field (you can implement it internally 
by creating another event and annotation or whatever suits you).

**Comment by mushon** [comment]
Would it be useful to have an option in an event admin "create child event" and then open a child event form with presenter end and disabled fields?

**Comment by yuvadm** [comment]
We decided to add a duplicate event button, track in #33
