### ISSUE TITLE
media types

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#27]
shouldn't it be much more basic ?
image, pdf, sound, movie, link ?
media type should appear in list

**Comment by mushon** [comment]
Also consider an image gallery as another media type (handled differently than multiple individual images)

**Comment by yuvadm** [comment]
It's redundant, we can already infer this from the file metadata (i.e. the file extension). We had two fields for this in the data model sketch, this is the other one.

**Comment by yuvadm** [comment]
We're gonna leave this as is with a single title/caption field. Categories can be finalized per #36

**Comment by josefspr** [comment]
aren't we deleting this field ?
