### ISSUE TITLE
Finalize project naming

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/data#3]
Some aspects to think about:
- how do we translate "da'at hamakom"?
- will the project have a unique name of its own?
- will project be served from http://daat-hamakom.com subdomain or it's own domain?

**Comment by josefspr** [comment]
Hi, I am still consulting regarding the name. 
I think it will be a subdomain of data-hamakom, does this need any authorisation ?

**Comment by yuvadm** [comment]
There's no problem with a subdomain, we'll just need to put in a request to whoever runs the existing site to hook up the subdomain to a value that I will provide.

**Comment by josefspr** [comment]
Write me the request and I'll forward it to the site managers

**Comment by josefspr** [comment]
Some thoughts regarding the name. Since the map is the legacy of the center, why not just call it Da'at Hamakom and subtitle "Map of Modern Jewish Culture". I don't think Da'at Hamakom should be translated, they did not do that on the site. What do you think ?

**Comment by josefspr** [comment]
Also talked to Edwin, right now lets leave it as it is
Name: Da'at Hamakom
Subtitle: A Map of Modern Jewish Culture

**Comment by mushon** [comment]
"Da'at Hamakom" is something even Hebrew speakers can hardly read, let alone English speakers which are our main audience. I think we should keep "Da'at Hamakom in the subtitle, but find something more communicative as a name. But that's not a big deal right now.

For now, I would suggest we don't close it, but rather don't make it a recent priority.

**Comment by yuvadm** [comment]
Agree with @mushon's feedback. The only "rush" that we'll want a domain name for everyone to start using as soon as possible.

This week I'll be deploying everything to http://daat-hamakom.herokuapp.com and I suggest that before we go live we create a subdomain such as http://maps.daat-hamakom.com/ or something similar that will map to the heroku domain.

**Comment by yuvadm** [comment]
For this milestone we'll go with https://daat-hamakom.herokuapp.com/

I'm pushing this back for decision in a later milestone.
