### ISSUE TITLE
Duplicate event button

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/data#33]

**Comment by josefspr** [comment]
change name to "duplicate event" or something like that. 
consider also adding to event list operations

**Comment by yuvadm** [comment]
Event list operations doesn't really make sense. Why would a user want to duplicate a bulk of events? They'd have to go ahead and manually edit them anyway, no reason to do this en masse.

**Comment by josefspr** [comment]
agree, but would like you to change button name in form to "duplicate event" makes more 
sense to me then save as new

**Comment by yuvadm** [comment]
sure
