### ISSUE TITLE
Directionality/origin field on Annotation

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/data#35]

**Comment by josefspr** [comment]
origin can be event not only place

**Comment by yuvadm** [comment]
If it's an event we can probably use other metadata to infer the origin (such as dates). I can't have a foreign key to place _or_ event. In any case I propose to continue with what we have and see how it comes up when we implement directionality.

**Comment by josefspr** [comment]
I understand - so in this case for now I prefer the choice for origin from the events, not places
