### ISSUE TITLE
Finalize all choice fields

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/data#36]

**Comment by yuvadm** [comment]
Just to reiterate, what we need here is a strict specification of every option in all choice fields in all models.

**Comment by josefspr** [comment]
annotations type: add "origin"

**Comment by josefspr** [comment]
annotations type: add "origin"

**Comment by yuvadm** [comment]
@josefspr I don't understand your

**Comment by yuvadm** [comment]
> annotations type: add "origin"

@josefspr I don't understand this

**Comment by josefspr** [comment]
type menu: correspondence, group, travel, trend, reference, origin
