### ISSUE TITLE
Add polygon support for Places

### ISSUE THREAD

**Issue by yuvadm** [daat-hamakom/data#37]
Support GeoJSON field

**Comment by josefspr** [comment]
the geojson string changes when saved

**Comment by yuvadm** [comment]
yep, formatting and redundant whitespace is removed, is this a problem? Keep in mind users aren't expected to edit the JSON by hand, just copy-pasta from geojson.

**Comment by josefspr** [comment]
I think it switched the order of the string, but never mind lets debug it on the map when we get there

**Comment by yuvadm** [comment]
It's reasonable that objects within the JSON move around after being parsed, but this doesn't change the object semantics.
