### ISSUE TITLE
remove institution field from research

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#44]
"Supported by" suffices, sorry...

**Comment by josefspr** [comment]
field still there...

**Comment by yuvadm** [comment]
where do you see it?

**Comment by josefspr** [comment]
In projects

**Comment by yuvadm** [comment]
Oh, I removed `research_field`. Should I remove both, or should I put it back and remove `institution` instead?

**Comment by josefspr** [comment]
remove institution
instead of research field put keywords

**Comment by yuvadm** [comment]
keywords per #47
