### ISSUE TITLE
Select2 tagging widget for `keyword` ArrayFields

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#47]
I think it is more clear to have this as a standard field

**Comment by yuvadm** [comment]
what is this field? does this cover the tagging capability we discussed? wasn't that just for events? please clarify.

**Comment by josefspr** [comment]
for persons we talked about putting tags in title field, I prefer not, that title is (rabbi, dr. etc) and there
will be a tags fields call keywords or tags
for organizations rename field "type" 
for projects rename "research field"

**Comment by yuvadm** [comment]
Branch `select2` has work being done on the tagging widget

**Comment by yuvadm** [comment]
Pending https://github.com/applegrew/django-select2/issues/226

**Comment by josefspr** [comment]
ok, we can add this later when you get on top of this

**Comment by yuvadm** [comment]
Merged `select2` branch. We have a working tag widget on `Place` alt_name fields.

**Comment by yuvadm** [comment]
Added also for `Person` alt_name

**Comment by josefspr** [comment]
what about keyword field in the event ?

**Comment by yuvadm** [comment]
what's that? Please open a new ticket if it's something new that's not related to this change.
