### ISSUE TITLE
projects list fields and filters 

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#51]
fields: title, subtitle, researcher
filters: creator, researcher

**Comment by josefspr** [comment]
missing researcher in list view and filter

**Comment by yuvadm** [comment]
Researcher is not missing in the filter. I added Marie Curie and now you see it. Django is smart in this regard and hides filters if there's only one option. As for the list view, per #49 we can't have a M2M in the list view.

**Comment by yuvadm** [comment]
Closing. Continue tracking on #49
