### ISSUE TITLE
link type in media

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#55]
do we need to add it ?

**Comment by yuvadm** [comment]
Nope, as you can see (in the list view) it's auto generated and uneditable by design.

**Comment by josefspr** [comment]
No, I was meaning a url media type in addition to sound, image, video and document

**Comment by josefspr** [comment]
don't forget to remove the "link type" field (its confusing ...)

**Comment by yuvadm** [comment]
What do you mean by a URL type?

**Comment by josefspr** [comment]
a link to a webpage url, although we can do that also byputting a link in the description.mushon, what do you think ?

Date: Mon, 23 Nov 2015 01:45:05 -0800

**Comment by yuvadm** [comment]
From the data model perspective, a media object only makes sense for an uploaded file. There's no use for throwing metadata around a URL in this case.

**Comment by yuvadm** [comment]
Fixed in #57
