### ISSUE TITLE
media - movie should also be a link (youtube, etc...)

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#57]
This will be the standard in most cases.

**Comment by josefspr** [comment]
source url covers this case but the file is not obligatory. will it be able to distinguish the link
as a movie ? also what about images/manuscripts that are online links like:
http://jpress.org.il/Olive/APA/NLI_heb/SharedView.Article.aspx?parm=yK3drlZkPb6rNl0nVOHlWRMvpq4bbZXBjErUrPjnoJSol2SM7M36GO7SbAj2xtJWYw%3D%3D&mode=image&href=HMA%2F1905%2F10%2F13&page=9&rtl=true

**Comment by yuvadm** [comment]
Files like that should be saved and uploaded to our media repo (unless there's some kind of copyright issue). As I've said before, links are not media items and I don't think we need a special model around them. Need to see where this comes up in the UI/UX and then decide how to approach this.

**Comment by josefspr** [comment]
In wordpress you can add a link as a movie. Saving and uploading will be a large overhead to researchers to do this.

**Comment by yuvadm** [comment]
I understand, we will definitely support this flow, but links are not media items :)

**Comment by josefspr** [comment]
from the researcher's pov and the event card, they are media items...

**Comment by yuvadm** [comment]
OK. Added an optional URL field.

**Comment by josefspr** [comment]
sorry the reopen this, but I think that a movie link should be specified as so, since it will be 
displayed in an embedded form.

**Comment by josefspr** [comment]
sorry the reopen this, but I think that a movie link should be specified as so, since it will be 
displayed in an embedded form.

**Comment by yuvadm** [comment]
complete overkill, there's no need to specify this explicitly. when we pull media items we can be intelligent about how to display them (i.e. a media item with no file and a URL pointing to youtube will be rendered as such)

**Comment by josefspr** [comment]
ok. only that in the event card a movie link should appear as one.

**Comment by yuvadm** [comment]
of course, we still have full flexibility as to how we display links.
