### ISSUE TITLE
Edit media from event

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#63]
This would help very much to access specific media object to edit details.

**Comment by yuvadm** [comment]
This is not possible with the selection widget we currently use. I'll keep this open as an improvement, but I don't have a nice way to solve this right now.

**Comment by yuvadm** [comment]
Of course new media items can be added by clicking on the green plus link on the right side of the widget

**Comment by josefspr** [comment]
can we filter the media by the event they appear in that would be an alternative solution

**Comment by yuvadm** [comment]
We can already filter media by project, is that not enough? If I add filter by event it'll create a possibly unreasonably-long filter list

**Comment by josefspr** [comment]
We cannot filter by project. If you can do that it will suffice

**Comment by yuvadm** [comment]
Indeed, my mistake. I'll add that.
