### ISSUE TITLE
Preview mode

### ISSUE THREAD

**Issue by josefspr** [daat-hamakom/data#9]
Can we add to the all records draft/publish mode ? and that the researcher can view the
map in preview mode displaying the records in draft mode ?

**Comment by yuvadm** [comment]
We can possibly add some rudimentary flag on Events marking them as unpublished or something like that. @mushon do you think this makes sense?

**Comment by mushon** [comment]
I do.

**Comment by yuvadm** [comment]
And the crowd goes wild!

**Comment by yuvadm** [comment]
Added flag in 569e407

**Comment by josefspr** [comment]
So how does it work, do you have a publish button to toggle between published/unpublished?

**Comment by yuvadm** [comment]
Yes, it's just another field on each event that you need to toggle. Of course we'll have the option to select a bulk of events and toggle them together.

**Comment by yuvadm** [comment]
Added all the relevant `published` functionality in the admin, including field and admin action (select many and choose "mark events as published")
